version: '2'

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    rules:
      - path: test/
        linters:
          - gosec
        text: "G204" # subprocess launched with variable
      - path: test/
        linters:
          - gosec
        text: "G304" # potential file inclusion via variable
      - path: test/utils/
        linters:
          - revive
        text: "var-naming" # the package name `utils` is fine here

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(k8s.io)
        - prefix(sigs.k8s.io/controller-runtime)
        - prefix(sigs.k8s.io/multicluster-runtime)
        - prefix(github.com/platform-mesh)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: disable
