apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- deployment.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/resource-broker
  newTag: latest@sha256:f22f905ff0ade89cd99c8d31329d92dcc2c9eca82b794fee4447b785f77779fa
