apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- deployment.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/resource-broker
  newTag: latest@sha256:9a6e21ea2d180c6238ae0cf72f62c7dce77ecf6cb66eb3cdd96ce0914c5addbb
