apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- deployment.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/resource-broker
  newTag: latest@sha256:123c9b7a7f2c26dcef3907db25b8e1131a63e9358bc86f0c62fc4f04337d9adf
