apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
    ui.platform-mesh.io/content-for: generic.platform-mesh.io
  name: resource-broker-ui
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "resource-broker-ui",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "pathSegment": "generic-apis",
                          "label": "Generic APIs Broker",
                          "hideFromNav": false,
                          "icon": "database",
                          "url": "https://{context.organization}.portal.localhost:8443/resource-broker/",
                          "entityType": "main.core_platform-mesh_io_account",
                          "order": 900,
                          "loadingIndicator": {
                              "enabled": true
                          },
                          "context": {
                              "accountId": ":core_platform-mesh_io_accountId"
                          }
                      }
                  ]
              }
          }
      }
    contentType: json
