name: Trivy SBOM Scan

on:
  schedule:
    # Run every day at 04:30 UTC
    - cron: '30 4 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  scan-sbom:
    uses: platform-mesh/.github/.github/workflows/job-trivy-sbom.yml@75f52df7bff585bcb2d794a7bbeec132354933fb # main
    permissions:
      contents: read
      packages: read
      security-events: write
